In [1]:
import pandas as pd
pd. get_option("display.max_columns")
Originals = pd.read_csv('../Data/Netflix Originals.csv', encoding='latin-1')
Titles = pd.read_csv('../Data/Netflix Titles.csv', encoding='latin-1')

In [2]:
Originals.head(3)

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian

In [3]:
Originals['Title'] = Originals['Title'].str.replace(' ', '').replace('-', '').replace('&', '').replace(',', '').replace('!', '').replace('.', '').str.lower()
Originals.head(3)

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,entertheanime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,darkforces,Thriller,"August 21, 2020",81,2.6,Spanish
2,theapp,Science fiction/Drama,"December 26, 2019",79,2.6,Italian

In [4]:
Originals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       584 non-null    object
 1   Genre       584 non-null    object
 2   Premiere    584 non-null    object
 3   Runtime     584 non-null    int64
 4   IMDB Score  584 non-null    float64
 5   Language    584 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 27.5+ KB

In [5]:
Titles.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [6]:
Titles['title'] = Titles['title'].str.replace(' ', '').replace('-', '').replace('&', '').replace(',', '').replace('!', '').replace('.', '').str.lower()
Titles.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,dickjohnsonisdead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,blood&water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [7]:
Titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [8]:
Data = Originals.merge(Titles, left_on = 'Title', right_on = 'title')
Data = Data[Data['country'].notna() & Data['rating'].notna() & (Data['type'] == 'Movie')]
Data = Data[['Title', 'Genre', 'Runtime', 'IMDB Score', 'Language', 'country', 'release_year', 'rating']]
Data.head(3)

,Title,Genre,Runtime,IMDB Score,Language,country,release_year,rating
0,entertheanime,Documentary,58,2.5,English/Japanese,"United States, Japan",2019,TV-MA
1,darkforces,Thriller,81,2.6,Spanish,Mexico,2020,TV-MA
2,theapp,Science fiction/Drama,79,2.6,Italian,Italy,2019,TV-MA

In [9]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 526 entries, 0 to 541
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         526 non-null    object
 1   Genre         526 non-null    object
 2   Runtime       526 non-null    int64
 3   IMDB Score    526 non-null    float64
 4   Language      526 non-null    object
 5   country       526 non-null    object
 6   release_year  526 non-null    int64
 7   rating        526 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 37.0+ KB

In [10]:
%store Data

Stored 'Data' (DataFrame)